# Generated by Django 4.1.2 on 2022-10-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='rating',
            field=models.SmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=5, verbose_name='Rating'),
        ),
    ]
